[profile.default]
solc_version = "0.8.31"
evm_version = "prague"

optimizer = true
optimizer_runs = 20

via_ir = true

remappings = [
  "@solady=lib/solady/",
  "@soledge=lib/soledge/",
  "@forge=lib/forge-std/src/",
  "@zamm=lib/ZAMM/src/"
]

[profile.via-ir]
via_ir = true

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://eth-mainnet.public.blastapi.io"